### ISSUE TITLE
Global installation and absolute paths

### ISSUE THREAD

**Issue by prettydiff** [reid/node-jslint#145]
I cannot get this to work with absolute paths from a global installation.

    npm install jslint -g
    jslint /Users/acheney/node_modules/prettydiff/prettydiff.js

The above code returns a 0 length string.  If I were to run it against just a file name, `prettydiff.js` then it works as expected.  It seems this module can read from relative paths perfectly as expected but fails on absolute paths and returns nothing (not even an error).

This problem has additional consequences in some application environments were Node is run as a secondary process of something else, such as many of the new JavaScript based code editors.  In this scenario Node execution is dependent upon a higher order process and as such loses its execution context with regards to the file system so process.cwd() becomes root, or "/" in posix and "c:\" in windows.

Before I go any further, let me explain some distinctions:

* `process.cwd()` - This identifies the current working directory, as in where on the command prompt the user executes the current Node process without regard for where in the file system that code resides.
* `__dirname` - This identifies the directory in which the current Node application resides at execution time.

I encountered and solved for this problem in my own project about a month ago.  The goal is to resolve file paths regardless of whether absolute or local.  It is easier to normalize everything to an absolute path than a relative path, particularly when `process.cwd()` gets lost.  Here is what you have to do:

1. Identify if `process.cwd` is root.  I do this at: https://github.com/prettydiff/prettydiff/blob/master/api/node-local.js#L35-L36
2. If cwd is root it is worthless, so I just use Line 37 to instead use `__dirname`.

The key take away here are to test if cwd is root, differently depending upon the OS, and then instead use __dirname.

**Comment by smikes** [comment]
Thanks for your bug report, and my apologies for taking so long to respond.

The root cause of the behavior you are seeing is the presence of the path element "node_modules" in the full path.  `node-jslint` skips linting files that have `node_modules` in their path, because those are usually not the files in the project you want to lint.  I am not thrilled with this behavior, especially since I put it there in the first place and now regret it, but removing it would be a breaking change, so I'm leaving it for now.

You can disable this "feature" by running `jslint --no-filter`, e.g. --

```
jslint --no-filter ${PWD}/foo.js

/Users/smikes/src/github/node_modules/foo.js is OK.
```

**Comment by prettydiff** [comment]
Thank you.
